[package]
name = "sweep"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
repository.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
bon = { version = "3.6.4", default-features = false }
common = { version = "0.1.0", path = "../../common" }
controller = { version = "0.1.0", path = "../../ui/controller" }
eframe = { version = "0.31.1", default-features = false }
egui_extras = { version = "0.31.1", default-features = false }
intersection_table = { version = "0.1.0", path = "../../ui/intersection_table" }
ordered-float = "5.0.0"
segment_plotter = { version = "0.1.0", path = "../../ui/segment_plotter" }
segment_table = { version = "0.1.0", path = "../../ui/segment_table" }
serde = { version = "1.0.219", features = ["derive"], optional = true }

[lints]
workspace = true

[dev-dependencies]
googletest = "0.14.1"

[features]
serde = [
    "dep:serde",
    "ordered-float/serde",
    "common/serde",
    "segment_plotter/serde",
    "segment_table/serde",
    "intersection_table/serde",
]
