[package]
name = "voronoi"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
repository.workspace = true
description.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
common = { version = "1.0.0", path = "../../common", features = ["float"]}
priority-queue = "2.5.0"
site_table = { path = "../../ui/site_table" }
controller = { path = "../../ui/controller" }
eframe = { version = "0.31.1", default-features = false }
egui_plot = "0.32.1"
egui_extras = { version = "0.31.1", default-features = false }
slotmap = "1.0.7"
itertools = "*"
[lints]
workspace = true
