name: Changelog + Benchmark

# By default, runs if you push to main. Exclude CHANGELOG so we do not write infinite times.
on:
  push:
    branches:
      - main
    paths-ignore:
    - 'CHANGELOG.md'
    - 'benchmark/out/**'
permissions:
  contents: write # for committing to gh-pages branch.

jobs:
  changelog_and_benchmark:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-hakari
        uses: taiki-e/install-action@v2 # v2
        with:
          tool: cargo-hakari
      - name: disable hakari
        run: cargo hakari disable
      - name: Benchmark
        working-directory: ./benchmark
        run: cargo bench -q --benches > out/${{ github.event.repository.updated_at}}-${{github.sha }}

      - name: Commit
        run: |
          git checkout ${GITHUB_REF##*/}
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add benchmark/out/${{ github.event.repository.updated_at}}-${{github.sha }}
          git add CHANGELOG.md
          git commit -m "chore(cliff): Update changelog"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git ${GITHUB_REF##*/}